### ISSUE TITLE
Issues with --svoast-max-width

### ISSUE THREAD

**Issue by NormandoHall** [Gibbu/svoast#5]
Hi. Thanks for this nice toast!

The issue is about max-width and line breakings.

Default:

![image](https://user-images.githubusercontent.com/2943127/235328706-699ddcfd-8cd6-433b-898a-e5c72eaa18be.png)

Default with line break `<br />` in text:

![image](https://user-images.githubusercontent.com/2943127/235328793-a0cc84b2-607d-4122-bf90-0092f551a374.png)

As you can see, the left icon is not vertical aligned. 

Setting  `--svoast-max-width: 18rem` without line break

![image](https://user-images.githubusercontent.com/2943127/235328742-9a5c576d-b98f-4e01-8d86-e221f00859a2.png)

The same as previous, but icon is also reduced. And close icon right is reduced.

It'll be great if the icon is vertical aligned and hold the same size.

**Comment by Gibbu** [comment]
Fixed with `svoast@2.1.1` 👍
